### ISSUE TITLE
Make SVG of logo

### ISSUE THREAD

**Issue by RichardWalker80** [PandaRedaction/panda_redaction#11]

**Comment by RichardWalker80** [comment]
![Image](https://user-images.githubusercontent.com/118642247/205490937-97874523-d08e-4c98-b7b7-dacdc18f6883.svg)

**Comment by anthonyrjwood** [comment]
![Image](https://user-images.githubusercontent.com/56207374/205492278-21f47125-e74e-40fc-b35e-78a0dbd66694.png)

**Comment by anthonyrjwood** [comment]
This doesn't function properly as an SVG. Seems to be missing some bits when opened up.

**Comment by RichardWalker80** [comment]
Thanks man,  i'll check it

**Comment by RichardWalker80** [comment]
!

**Comment by anthonyrjwood** [comment]
![Image](https://user-images.githubusercontent.com/56207374/206434498-d5d91f67-8f7f-4ee3-a2f3-41e41bb31835.svg)

**Comment by anthonyrjwood** [comment]
![Image](https://user-images.githubusercontent.com/56207374/206434535-a53391a0-7c60-4ef0-8d76-bba5e0788215.svg)
